In [1]:
import pandas as pd

In [2]:
df_goleadores = pd.read_excel("datos/Goleadores.xlsx")
df_goleadores

            Nombre  Goles Posición         Equipo   Año
0       K. Benzema     27      DEL    Real Madrid  2022
1       Iago Aspas     17      DEL          Celta  2022
2    Raúl De Tomás     17      DEL       Espanyol  2022
3     Vinicius Jr.     17      DEL    Real Madrid  2022
4           Juanmi     16      DEL     Real Betis  2022
..             ...    ...      ...            ...   ...
435       J. Carew     11      DEL       Valencia  2001
436      R. Tamudo     11      DEL       Espanyol  2001
437       S. Eto'o     11      DEL       Mallorca  2001
438    J. Esnáider     11      DEL  Real Zaragoza  2001
439  E. Jankauskas     11      DEL    R. Sociedad  2001

[440 rows x 5 columns]

In [3]:
df_goleadores.to_csv("data/df_Goleadores.csv", index=False)